name: Deploy

on:
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_MOVIE_DB_ACCESS_TOKEN: ${{ secrets.MOVIE_DB_ACCESS_TOKEN }}

    steps:      
      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
      - name: Deploy using Terraform
        working-directory: ./terraform
        run: |          
          terraform init
          terraform validate
          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/movie-match-rg
          terraform apply -auto-approve